### ISSUE TITLE
Cannot Cut & Paste between terminal tabs using keyboard/mouse events

### ISSUE THREAD

**Issue by nuxy** [mate-desktop/mate-terminal#239]
#### Expected behaviour

_Cut & Paste_ between terminal windows work.

#### Actual behaviour

Cannot _Cut & Paste_ using the keyboard `[CTRL-C/CTRL-V]` or using right-click mouse events.

#### Steps to reproduce the behaviour

1. Launch MATE Terminal with two tabs in the same window.
2. `[CTRL-C]` or _Right-click / Copy_ text from tab 1
3. `[CTRL-V]` or _Right-click / Paste_ text to tab 2
4. Empty result is pasted in the terminal window.

#### Additional notes ####
- _Copy & Paste_ works when the text comes from anything other than a MATE Terminal window, for example an external text document.
- MATE Terminal option "Copy selected text to clipboard" is enabled for the profile.

#### MATE general version

1.12.1

#### Package version

16.04.4 (Xenial Xerus)

#### Linux Distribution

Unbuntu 16.04 (Xenia) LTS

**Comment by uvwild** [comment]
its seariously a pane in the ass. I am so used to copy things around between terminal windows....
And then I installed Mate terminal and it stops working as usual.
It seems that every terminal window inits the copy paste buffer and doesnt share anything with other tabs. 
it does not seem to be user account related (as use a number of unix user shells)
Sometimes the middle click still works but the terminal menu and key commands are seriously broken.
That is on 1.16.3.
Please let me know how to install just the new current version of the mate terminal so I can verify that the bug is still there.

**Comment by sc0w** [comment]
I can copy/paste between tabs and windows with mate-terminal 1.20.0 using keyboard and mouse

Note: the default keys to copy/paste are: [ctrl+shift+C] and [ctrl+shift+V] and you can modify it  in [edit -> keyboard shortcuts]

**Comment by msmouse** [comment]
Sometimes a tab seems to get it's own clipboard: 
Within the tab, copy by selection, keyboard shortcuts or menu clicks wrt copy&paste work as expected. But it doesn't feed the value to the "global clipboard", i.e. either other tabs nor other applications see the clipboard change, nor are values of the global clipboard reflected in that tab.

**Comment by uvwild** [comment]
> I can copy/paste between tabs and windows with mate-terminal 1.20.0 using keyboard and mouse
> 
> Note: the default keys to copy/paste are: [ctrl+shift+C] and [ctrl+shift+V] and you can modify it in [edit -> keyboard shortcuts]

How do you do it? Whats your system? 
I just installed a new ubuntu 18.04 and have the same problem again. It drives me crazy. 
No copying between tabs using menu or keyboard.
The mouse middle click is the only thing that works.

**Comment by vkareh** [comment]
Seems like the `PRIMARY` clipboard works just fine, but the `CLIPBOARD` clipboard only works per-tab.

**Comment by vkareh** [comment]
The issue seems to be with the `copy-selection` gsettings... when set to `true`, any time that the terminal screen changes (changing tab, or focus away or to it), it updates the clipboard to any selected text. If no text is selected, it copies empty text... disabling `copy-selection` (go into "Profile Preferences" and uncheck "Copy selected text into clipboard") fixes it for me.

Seems like the `copy-selection` feature needs some rework

**Comment by hybroid** [comment]
Amazing! It works for me too!

**Comment by koppor** [comment]
Here, it does not work even though "copy-selection" is activated

![image](https://github.com/mate-desktop/mate-terminal/assets/1366654/be4c1322-242d-4dc7-a26f-af89a7b9661e)

Edit /  Copy is grayed-out.

**Comment by linas** [comment]
See also https://github.com/mate-desktop/mate-terminal/issues/68
