### ISSUE TITLE
CI: meson build is broken with debian

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-terminal#411]
#### Expected behaviour
CI: meson build runs fine with debian

#### Actual behaviour
CI: meson build is broken with debian

#### Steps to reproduce the behaviour
see https://app.travis-ci.com/github/mate-desktop/mate-terminal/jobs/559501430#L9243

#### MATE general version
Mate Master

#### Package version
Mate Master

#### Linux Distribution
master isn't released

#### Link to bugreport of your Distribution (requirement)
master isn't released

**Comment by eli-schwartz** [comment]
https://github.com/mate-desktop/mate-terminal/blob/164a19370cba65fc5538ccd7e9a43cf7de7df226/meson.build#L179-L181

This `'desktop-file'` argument never did anything. Older versions of Meson simply ignored it altogether, but newer versions of Meson with better type-checking report that this function is neither documented nor expected to take an argument there, and error out.

In Meson 0.60.1 it was allowed to work, but would log a deprecation warning. This was done as a favor to various Gnome projects which all made this mistake, in order to raise awareness while giving them another couple of months to deploy a fix. In Meson 0.62.0 it is back to being an error.

You can see the deprecation warning in the most recent commit here before today: https://app.travis-ci.com/github/mate-desktop/mate-terminal/jobs/551833535#L10750

**Comment by raveit65** [comment]
@eli-schwartz 
So simply removing `desktop-file`argument is the correct way to fix it?

**Comment by raveit65** [comment]
Removing the argument doesn't fix the problem.
PR : https://github.com/mate-desktop/mate-terminal/commit/d104f379f33e9115e06de9a107ae3ccf6e66e8ba
https://app.travis-ci.com/github/mate-desktop/mate-terminal/jobs/560456729#L9350

**Comment by eli-schwartz** [comment]
Sure it fixes the problem. Before you got this error:

```
Configuring mate-terminal.desktop.in using configuration

meson.build:179:0: ERROR: Function does not take positional arguments.
```

Now, after fixing line 179, you get this error:
```
Configuring mate-terminal.appdata.xml.in using configuration

meson.build:210:0: ERROR: Function does not take positional arguments.
```

Please draw your own conclusions. :)

**Comment by raveit65** [comment]
I am not familiar with meson and i don't know to fix the build issue . All i see that it runs fine with fedora on the same build
https://app.travis-ci.com/github/mate-desktop/mate-terminal/jobs/560456730#L3586
If you know to fix it please provide a PR.

**Comment by eli-schwartz** [comment]
The same error appears on two different lines, both use i18n.merge_file and both have a positional argument which is not allowed.

You removed the positional argument from one instance, the same error cropped up again on a different line -- so you need to remove the positional argument from the other instance too.

**Comment by raveit65** [comment]
Thanks for helping , now it builds fine at PR.
