### ISSUE TITLE
[Feature request]: Increase the font-size from 10 to 12

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/mate-terminal#440]
#### Expected behaviour
"[A clearly legible font of at least size 12 preferably in a dark color over light background should be chosen.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9434525/)"

#### Actual behaviour
The default font-size in mate-terminal for Ubuntu MATE 22.04 is 10.

#### Steps to reproduce the behaviour
Open mate-terminal

#### MATE general version
1.26.2

#### Package version
1.26.0

#### Link to bugreport of your Distribution (requirement)
* https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/2028301
* https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/95

**Comment by raveit65** [comment]
Blame ubuntu Mate , or use gsettings override as distro maintainer.

**Comment by davidhedlund** [comment]
Can you please tell me what the default font-size is for mate-terminal in this repo?

**Comment by raveit65** [comment]
Mate terminal use system settings or monospace 12.
![Bildschirmfoto zu 2023-07-20 20-25-34](https://github.com/mate-desktop/mate-terminal/assets/961604/aa6b228e-4231-423e-882c-f2411d8a3b1d)
I am packaging MATE since 2012 for fedora, but this question was never a problem.
And fedora use vanila MATE which is really a different to Ubuntu-Mate. 
You can customize Mate via gsettings overrides. This is mine.
https://src.fedoraproject.org/rpms/mate-desktop/blob/rawhide/f/mate-fedora-f34.gschema.override
Such a file needs to be installed to `%{_datadir}/glib-2.0/schemas/10_mate-fedora.gschema.override`

Btw, actual we are a very small team and you gave us a lot of work with your wish list.

**Comment by raveit65** [comment]
With `mate-appearance-properties` you can setup system font size.
![Bildschirmfoto zu 2023-07-20 20-41-40](https://github.com/mate-desktop/mate-terminal/assets/961604/e7c6b5c9-f7de-453e-a0b7-a10f1aa7316e)

**Comment by davidhedlund** [comment]
> Mate terminal use system settings or monospace 12.

This is exactly what I was looking for. Thank you very much!

**Comment by davidhedlund** [comment]
> And fedora use vanila MATE which is really a different to Ubuntu-Mate.

That is useful to know.

You can customize Mate via gsettings overrides. This is mine. https://src.fedoraproject.org/rpms/mate-desktop/blob/rawhide/f/mate-fedora-f34.gschema.override Such a file needs to be installed to `%{_datadir}/glib-2.0/schemas/10_mate-fedora.gschema.override`

I documented this at https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/95

Thanks again.
