### ISSUE TITLE
ctrl-shift-copy paste intermittently out

### ISSUE THREAD

**Issue by muttrudd** [mate-desktop/mate-terminal#68]
1. ctrl-c selected text from pluma or keepass
2. shift-ctrl-v into mate-terminal: no result
3. edit > paste into terminal: works
4. restart computer: normal copy and paste functionality in mate-terminal resumes. This will make the issue difficult to reproduce.

I copy and paste between applications into the terminal on a daily basis to check my email with mutt. I experienced the issue yesterday and today. I have mate desktop installed on top of stable Debian.

I see that there was a previous report on this issue,  but I am not sure that the problem was actually understood before the report was closed: https://github.com/mate-desktop/mate-terminal/issues/43

There is discussion in mate-forums: http://forums.mate-desktop.org/viewtopic.php?f=2&t=1510

Searching for this problem I see similar issues with gnome-terminal.

**Comment by monsta** [comment]
Can't reproduce this - paste shortcut always works for me. Does it still happen in 1.10?

**Comment by muttrudd** [comment]
Sorry, I'm not using Mate anymore (though I like it and will probably 
try it again sometime in the future.) If no one else had the problem I 
suggest closing the report. Best, Mutt

**Comment by thanatos** [comment]
Just a note, but I *also* experience this issue. However, I'm experiencing it in GNOME Terminal 2.32.1, not MATE terminal. (I keep meaning to switch to MATE terminal because MATE, but alas…)

**Comment by linas** [comment]
Ten years on, this is still not fixed. Based on a half-dozen stack-exchange posts, hundreds of people have this problem, and they see it on all distros and all releases. I'm personally running MATE in Debian Stable (12 "bookworm") and after a week, it just cuts out.  Suggestions for using `xsel`, `xclip`, uninstalling `clipit` don't work. (I never had any of these installed. I did just now experiment with `xsel` but it fixes nothing. 

Mate terminal menu -> clear does nothing. Further exploration shows none of the ctrl-shift functions work: not ctrl-shift-A (select all) ctrl-shift-F (find) ctrl-shift G, H (find previous, next) so its not limited t just cut-n-paste.  This suggests that the keyboard mapping for ctrl-shift gets mangled/broken during ordinary usage. I'm investigating this new plot twist now.

**Comment by binomaly** [comment]
Hello,

It is now 2026 an the problem is still there.

I keep my desktops always on. I do not reboot. I run VDI too. And sometimes the desktop is left there for a year or so.

The bug is really annoying. It comes occasionally and now in one of my laptops (using multiple).

mate-terminal-1.28.1 && F41

(1) Select text from firefox and then mouse middle works.
(2) Select text from mate-terminal it does not select of copying is done to some other buffer because after that middle mouse button paste the firefox text and menu paste paste the mate-terminal selected text. uh oh. would like to have only one buffer desktop (actually desktops i.e. if I have 20 VDI desktops on my desktop) wide.

Maybe mate-terminal text copy does work but it copies the text to another buffer than the buffer used for middle mouse paste.

//arl

**Comment by vkareh** [comment]
I've never had this issue, but whenever there are funky issues with shortcuts being swallowed (like Ctrl+Shift+C, for example) it usually is because of some other non-MATE application that has defined a conflicting global keybinding.

With regards to the various buffers, this is a Linux thing, not a mate-terminal thing: Linux has two main buffers:
- `CLIPBOARD`: populated with a specific action (Edit->Copy or Ctrl+C or Ctrl+Insert)
- `PRIMARY`: populated when selecting text

Now, for mate-terminal specifically, there are two quirks:
1. Because Ctrl-based shortcuts are already taken by VTE, many terminal emulators (mate-terminal, gnome-terminal, etc.) prefix a Shift to "popular" shortcuts, hence Ctrl+C for copy becomes Shift+Ctrl+C
2. Because of this confusion, we added a toggle that overrides the clipboard behavior so that the `CLIPBOARD` buffer is populated along with `PRIMARY`, that is, when selecting text:

<img width="473" alt="Image" src="https://github.com/user-attachments/assets/68ad065a-ce42-4e06-99f4-e1f5d922d354" />

Then separate from all that, there are TUI applications that mess around with text selection in the host terminal. Nothing we can do about that...

**Comment by linas** [comment]
> some other non-MATE application ...
> there are TUI applications ...

What other  non-MATE applications? Can we hunt these down and kill them? The search engines didn't know of any of these...

My desktop runs exactly two apps: `mate-terminal` and `firefox-esr` ... three, if you count `ssh`.  Four, if you count claude in a remote containerized sandbox. I cannot think of anything else, TUI or otherwise.

> Because Ctrl-based shortcuts are already taken by VTE,

ctrl-C and ctrl-H and ctrl-Z and ctrl-X and ctrl-D have been in use by terminals since before 1982, back when terminals were actual printing teletypes, or those cute little 1200 BAUD wax-paper printer-terminals you could take home with you. This predates Sun and Solaris; it was standard for VAX/VMS, so I don't think you can "blame" the VTE for this.

I assume that the use of ctrl-C for copying is yet another Microsoft hostility intentionally meant to screw with Sun and DEC (and IBM ...) users that was somewhat shamefully copied by the early gnome developers. Miguel de Icaza recruited a bunch of 16 and 17 year-olds for this; I think they just didn't know. I recall being in a coding blitz during some convention, it was very clear that the teens in the room kind of hated us "old farts" (the rest of us were 25 or 29 and were, like, married, or at least dating women. Whoops. Much too old to "get it", at any rate. Part of the old and brain-poisoned generation.)
